-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-05-02 02:39:06 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

SET ECHO ON
SPOOL ca_schema_output.txt

--student number: 35697601
--student name: Tuan Ngoc Chu

DROP TABLE BIN CASCADE CONSTRAINTS 
;

DROP TABLE BIN_TYPE CASCADE CONSTRAINTS 
;

DROP TABLE COLLECTION CASCADE CONSTRAINTS 
;

DROP TABLE COLLECTION_BIN CASCADE CONSTRAINTS 
;

DROP TABLE CONTRACT CASCADE CONSTRAINTS 
;

DROP TABLE CONTRACT_BIN CASCADE CONSTRAINTS 
;

DROP TABLE CONTRACT_WASTE CASCADE CONSTRAINTS 
;

DROP TABLE LOCAL_AUTHORITY CASCADE CONSTRAINTS 
;

DROP TABLE OWNER CASCADE CONSTRAINTS 
;

DROP TABLE PROPERTY CASCADE CONSTRAINTS 
;

DROP TABLE PROPERTY_OWNER CASCADE CONSTRAINTS 
;

DROP TABLE STREET CASCADE CONSTRAINTS 
;

DROP TABLE TRUCK CASCADE CONSTRAINTS 
;

DROP TABLE WASTE_TYPE CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE BIN 
    ( 
     bin_rfid               CHAR (24)  NOT NULL , 
     pro_id                 NUMBER (7)  NOT NULL , 
     ctb_id                 NUMBER (7)  NOT NULL , 
     bin_supply_date        DATE  NOT NULL , 
     bin_replacement_reason CHAR (2) 
    ) 
;

ALTER TABLE BIN 
    ADD CONSTRAINT chk_brr 
    CHECK (bin_replacement_reason IN ('BF', 'DO', 'DW', 'ST')) 
;

COMMENT ON COLUMN BIN.bin_rfid IS 'Bin RFID tag' 
;

COMMENT ON COLUMN BIN.pro_id IS 'Property ID' 
;

COMMENT ON COLUMN BIN.ctb_id IS 'Contract Bin ID' 
;

COMMENT ON COLUMN BIN.bin_supply_date IS 'Bin Supply Date' 
;

COMMENT ON COLUMN BIN.bin_replacement_reason IS 'Bin Replacement reason (DO-Damaged by owner, BF-Bin Failure, DW-Damaged during pickup of waste, ST-Stolen)' 
;

ALTER TABLE BIN 
    ADD CONSTRAINT BIN_PK PRIMARY KEY ( bin_rfid ) ;

CREATE TABLE BIN_TYPE 
    ( 
     bin_type_id              NUMBER (7)  NOT NULL , 
     bin_size                 NUMBER (3)  NOT NULL , 
     waste_type_id            NUMBER (7)  NOT NULL , 
     bin_standard_supply_cost NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN BIN_TYPE.bin_type_id IS 'Bin Type ID' 
;

COMMENT ON COLUMN BIN_TYPE.bin_size IS 'Bin Size' 
;

COMMENT ON COLUMN BIN_TYPE.waste_type_id IS 'Waste Type ID' 
;

COMMENT ON COLUMN BIN_TYPE.bin_standard_supply_cost IS 'Bin Standard Supply Cost' 
;

ALTER TABLE BIN_TYPE 
    ADD CONSTRAINT BIN_TYPE_PK PRIMARY KEY ( bin_type_id ) ;

ALTER TABLE BIN_TYPE 
    ADD CONSTRAINT BIN_TYPE_UQ UNIQUE ( bin_size , waste_type_id ) ;

CREATE TABLE COLLECTION 
    ( 
     collection_id   NUMBER (7)  NOT NULL , 
     contract_no     NUMBER (7)  NOT NULL , 
     waste_type_id   NUMBER (7)  NOT NULL , 
     collection_date DATE  NOT NULL , 
     truck_vin       VARCHAR2 (17)  NOT NULL 
    ) 
;

COMMENT ON COLUMN COLLECTION.collection_id IS 'Collection ID' 
;

COMMENT ON COLUMN COLLECTION.contract_no IS 'Contract Number' 
;

COMMENT ON COLUMN COLLECTION.waste_type_id IS 'Waste Type ID' 
;

COMMENT ON COLUMN COLLECTION.collection_date IS 'Collection Date' 
;

COMMENT ON COLUMN COLLECTION.truck_vin IS 'Truck VIN' 
;

ALTER TABLE COLLECTION 
    ADD CONSTRAINT COLLECTION_PK PRIMARY KEY ( collection_id ) ;

ALTER TABLE COLLECTION 
    ADD CONSTRAINT COLLECTION_UQ UNIQUE ( contract_no , waste_type_id , collection_date ) ;

CREATE TABLE COLLECTION_BIN 
    ( 
     bin_rfid          CHAR (24)  NOT NULL , 
     collection_id     NUMBER (7)  NOT NULL , 
     bin_collected_kgs NUMBER (3) , 
     bin_overweight    CHAR (1)  NOT NULL 
    ) 
;

ALTER TABLE COLLECTION_BIN 
    ADD CONSTRAINT chk_bo 
    CHECK (bin_overweight IN ('N', 'Y')) 
;

COMMENT ON COLUMN COLLECTION_BIN.bin_rfid IS 'Bin RFID tag' 
;

COMMENT ON COLUMN COLLECTION_BIN.collection_id IS 'Collection ID' 
;

COMMENT ON COLUMN COLLECTION_BIN.bin_collected_kgs IS 'Bin Collected in Kilograms' 
;

COMMENT ON COLUMN COLLECTION_BIN.bin_overweight IS 'Bin Overweight (Y-Yes, N-No)' 
;

ALTER TABLE COLLECTION_BIN 
    ADD CONSTRAINT COLLECTION_BIN_PK PRIMARY KEY ( bin_rfid, collection_id ) ;

CREATE TABLE CONTRACT 
    ( 
     contract_no         NUMBER (7)  NOT NULL , 
     authority_name      VARCHAR2 (50)  NOT NULL , 
     contract_start_date DATE  NOT NULL , 
     contract_end_date   DATE  NOT NULL 
    ) 
;

COMMENT ON COLUMN CONTRACT.contract_no IS 'Contract Number' 
;

COMMENT ON COLUMN CONTRACT.authority_name IS 'Authority Name' 
;

COMMENT ON COLUMN CONTRACT.contract_start_date IS 'Contract Start Date' 
;

COMMENT ON COLUMN CONTRACT.contract_end_date IS 'Contract End Date' 
;

ALTER TABLE CONTRACT 
    ADD CONSTRAINT CONTRACT_PK PRIMARY KEY ( contract_no ) ;

CREATE TABLE CONTRACT_BIN 
    ( 
     ctb_id                   NUMBER (7)  NOT NULL , 
     contract_no              NUMBER (7)  NOT NULL , 
     bin_type_id              NUMBER (7)  NOT NULL , 
     waste_type_id            NUMBER (7)  NOT NULL , 
     contract_bin_supply_cost NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CONTRACT_BIN.ctb_id IS 'Contract Bin ID' 
;

COMMENT ON COLUMN CONTRACT_BIN.contract_no IS 'Contract Number' 
;

COMMENT ON COLUMN CONTRACT_BIN.bin_type_id IS 'Bin Type ID' 
;

COMMENT ON COLUMN CONTRACT_BIN.waste_type_id IS 'Waste Type ID' 
;

COMMENT ON COLUMN CONTRACT_BIN.contract_bin_supply_cost IS 'Contract Bin Supply Cost' 
;

ALTER TABLE CONTRACT_BIN 
    ADD CONSTRAINT CONTRACT_BIN_PK PRIMARY KEY ( ctb_id ) ;

ALTER TABLE CONTRACT_BIN 
    ADD CONSTRAINT CONTRACT_BIN_UQ UNIQUE ( contract_no , bin_type_id ) ;

CREATE TABLE CONTRACT_WASTE 
    ( 
     contract_no            NUMBER (7)  NOT NULL , 
     waste_type_id          NUMBER (7)  NOT NULL , 
     collection_cost_per_kg NUMBER (7,2)  NOT NULL , 
     collection_freq        VARCHAR2 (20)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CONTRACT_WASTE.contract_no IS 'Contract Number' 
;

COMMENT ON COLUMN CONTRACT_WASTE.waste_type_id IS 'Waste Type ID' 
;

COMMENT ON COLUMN CONTRACT_WASTE.collection_cost_per_kg IS 'Collected Waste Cost per Kilogram' 
;

COMMENT ON COLUMN CONTRACT_WASTE.collection_freq IS 'Collection Frequency' 
;

ALTER TABLE CONTRACT_WASTE 
    ADD CONSTRAINT CONTRACT_WASTE_PK PRIMARY KEY ( contract_no, waste_type_id ) ;

CREATE TABLE LOCAL_AUTHORITY 
    ( 
     authority_name       VARCHAR2 (50)  NOT NULL , 
     authority_ceo_gname  VARCHAR2 (20)  NOT NULL , 
     authority_ceo_fname  VARCHAR2 (20)  NOT NULL , 
     authority_phone      VARCHAR2 (12)  NOT NULL , 
     authority_total_area NUMBER (7,2)  NOT NULL , 
     authority_type       CHAR (1)  NOT NULL 
    ) 
;

ALTER TABLE LOCAL_AUTHORITY 
    ADD CONSTRAINT chk_autyp 
    CHECK (authority_type IN ('B', 'C', 'D', 'S', 'T')) 
;

COMMENT ON COLUMN LOCAL_AUTHORITY.authority_name IS 'Authority Name' 
;

COMMENT ON COLUMN LOCAL_AUTHORITY.authority_ceo_gname IS ' Authority Chief Executive Officer''s Given Name' 
;

COMMENT ON COLUMN LOCAL_AUTHORITY.authority_ceo_fname IS ' Authority Chief Executive Officer''s Family  Name' 
;

COMMENT ON COLUMN LOCAL_AUTHORITY.authority_phone IS 'Authority Telephone' 
;

COMMENT ON COLUMN LOCAL_AUTHORITY.authority_total_area IS ' Authorities total area in square kilometres' 
;

COMMENT ON COLUMN LOCAL_AUTHORITY.authority_type IS 'Authority Type (B-Borough, C-City, D-District Council, S-Shire, T-Town)' 
;

ALTER TABLE LOCAL_AUTHORITY 
    ADD CONSTRAINT LOCAL_AUTHORITY_PK PRIMARY KEY ( authority_name ) ;

CREATE TABLE OWNER 
    ( 
     owner_id    NUMBER (7)  NOT NULL , 
     owner_name  VARCHAR2 (50)  NOT NULL , 
     owner_email VARCHAR2 (50)  NOT NULL , 
     owner_phone VARCHAR2 (12)  NOT NULL 
    ) 
;

COMMENT ON COLUMN OWNER.owner_id IS 'Owner ID' 
;

COMMENT ON COLUMN OWNER.owner_name IS 'Owner Name' 
;

COMMENT ON COLUMN OWNER.owner_email IS 'Owner Email' 
;

COMMENT ON COLUMN OWNER.owner_phone IS 'Owner Phone Number' 
;

ALTER TABLE OWNER 
    ADD CONSTRAINT OWNER_PK PRIMARY KEY ( owner_id ) ;

CREATE TABLE PROPERTY 
    ( 
     pro_id         NUMBER (7)  NOT NULL , 
     street_id      NUMBER (7)  NOT NULL , 
     authority_name VARCHAR2 (50)  NOT NULL , 
     street_no      NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PROPERTY.pro_id IS 'Property ID' 
;

COMMENT ON COLUMN PROPERTY.street_id IS 'Street ID' 
;

COMMENT ON COLUMN PROPERTY.authority_name IS 'Authority Name' 
;

COMMENT ON COLUMN PROPERTY.street_no IS 'Street Number' 
;

ALTER TABLE PROPERTY 
    ADD CONSTRAINT PROPERTY_PK PRIMARY KEY ( pro_id ) ;

ALTER TABLE PROPERTY 
    ADD CONSTRAINT PROPERTY_UQ UNIQUE ( street_id , authority_name , street_no ) ;

CREATE TABLE PROPERTY_OWNER 
    ( 
     owner_id NUMBER (7)  NOT NULL , 
     pro_id   NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PROPERTY_OWNER.owner_id IS 'Owner ID' 
;

COMMENT ON COLUMN PROPERTY_OWNER.pro_id IS 'Property ID' 
;

ALTER TABLE PROPERTY_OWNER 
    ADD CONSTRAINT PROPERTY_OWNER_PK PRIMARY KEY ( owner_id, pro_id ) ;

CREATE TABLE STREET 
    ( 
     authority_name  VARCHAR2 (50)  NOT NULL , 
     street_id       NUMBER (7)  NOT NULL , 
     street_name     VARCHAR2 (50)  NOT NULL , 
     street_length   NUMBER (7,2)  NOT NULL , 
     street_surface  CHAR (1)  NOT NULL , 
     street_no_lanes NUMBER (7)  NOT NULL 
    ) 
;

ALTER TABLE STREET 
    ADD CONSTRAINT chk_strlgth 
    CHECK (street_surface IN ('A', 'C', 'U')) 
;

COMMENT ON COLUMN STREET.authority_name IS 'Authority Name' 
;

COMMENT ON COLUMN STREET.street_id IS 'Street ID' 
;

COMMENT ON COLUMN STREET.street_name IS 'Street Name' 
;

COMMENT ON COLUMN STREET.street_length IS 'Street Length in meter' 
;

COMMENT ON COLUMN STREET.street_surface IS 'Street Surface (A-Asphalt, C-Concrete, U-Unsealed)' 
;

COMMENT ON COLUMN STREET.street_no_lanes IS 'Number of Lanes on Street' 
;

ALTER TABLE STREET 
    ADD CONSTRAINT STREET_PK PRIMARY KEY ( street_id, authority_name ) ;

CREATE TABLE TRUCK 
    ( 
     truck_vin   VARCHAR2 (17)  NOT NULL , 
     truck_rego  VARCHAR2 (10)  NOT NULL , 
     truck_make  VARCHAR2 (12)  NOT NULL , 
     truck_model VARCHAR2 (12)  NOT NULL , 
     truck_year  NUMBER (4)  NOT NULL 
    ) 
;

COMMENT ON COLUMN TRUCK.truck_vin IS 'Truck VIN' 
;

COMMENT ON COLUMN TRUCK.truck_rego IS 'Truck Rego' 
;

COMMENT ON COLUMN TRUCK.truck_make IS 'Truck Make' 
;

COMMENT ON COLUMN TRUCK.truck_model IS 'Truck Model' 
;

COMMENT ON COLUMN TRUCK.truck_year IS 'Truck Year' 
;

ALTER TABLE TRUCK 
    ADD CONSTRAINT TRUCK_PK PRIMARY KEY ( truck_vin ) ;

CREATE TABLE WASTE_TYPE 
    ( 
     waste_type_id   NUMBER (7)  NOT NULL , 
     waste_type_desc VARCHAR2 (20)  NOT NULL 
    ) 
;

COMMENT ON COLUMN WASTE_TYPE.waste_type_id IS 'Waste Type ID' 
;

COMMENT ON COLUMN WASTE_TYPE.waste_type_desc IS 'Waste Type Description' 
;

ALTER TABLE WASTE_TYPE 
    ADD CONSTRAINT WASTE_TYPE_PK PRIMARY KEY ( waste_type_id ) ;

ALTER TABLE CONTRACT 
    ADD CONSTRAINT authority_contract_fk FOREIGN KEY 
    ( 
     authority_name
    ) 
    REFERENCES LOCAL_AUTHORITY 
    ( 
     authority_name
    ) 
;

ALTER TABLE STREET 
    ADD CONSTRAINT authority_street_fk FOREIGN KEY 
    ( 
     authority_name
    ) 
    REFERENCES LOCAL_AUTHORITY 
    ( 
     authority_name
    ) 
;

ALTER TABLE COLLECTION_BIN 
    ADD CONSTRAINT bin_cb_fk FOREIGN KEY 
    ( 
     bin_rfid
    ) 
    REFERENCES BIN 
    ( 
     bin_rfid
    ) 
;

ALTER TABLE CONTRACT_BIN 
    ADD CONSTRAINT bty_cbt_fk FOREIGN KEY 
    ( 
     bin_type_id
    ) 
    REFERENCES BIN_TYPE 
    ( 
     bin_type_id
    ) 
;

ALTER TABLE COLLECTION_BIN 
    ADD CONSTRAINT collection_cb_fk FOREIGN KEY 
    ( 
     collection_id
    ) 
    REFERENCES COLLECTION 
    ( 
     collection_id
    ) 
;

ALTER TABLE CONTRACT_WASTE 
    ADD CONSTRAINT ct_ctw_fk FOREIGN KEY 
    ( 
     contract_no
    ) 
    REFERENCES CONTRACT 
    ( 
     contract_no
    ) 
;

ALTER TABLE BIN 
    ADD CONSTRAINT ctb_bin_fk FOREIGN KEY 
    ( 
     ctb_id
    ) 
    REFERENCES CONTRACT_BIN 
    ( 
     ctb_id
    ) 
;

ALTER TABLE COLLECTION 
    ADD CONSTRAINT ctw_collection_fk FOREIGN KEY 
    ( 
     contract_no,
     waste_type_id
    ) 
    REFERENCES CONTRACT_WASTE 
    ( 
     contract_no,
     waste_type_id
    ) 
;

ALTER TABLE CONTRACT_BIN 
    ADD CONSTRAINT ctw_ctb_fk FOREIGN KEY 
    ( 
     contract_no,
     waste_type_id
    ) 
    REFERENCES CONTRACT_WASTE 
    ( 
     contract_no,
     waste_type_id
    ) 
;

ALTER TABLE PROPERTY_OWNER 
    ADD CONSTRAINT owner_po_fk FOREIGN KEY 
    ( 
     owner_id
    ) 
    REFERENCES OWNER 
    ( 
     owner_id
    ) 
;

ALTER TABLE BIN 
    ADD CONSTRAINT pro_bin_fk FOREIGN KEY 
    ( 
     pro_id
    ) 
    REFERENCES PROPERTY 
    ( 
     pro_id
    ) 
;

ALTER TABLE PROPERTY_OWNER 
    ADD CONSTRAINT property_po_fk FOREIGN KEY 
    ( 
     pro_id
    ) 
    REFERENCES PROPERTY 
    ( 
     pro_id
    ) 
;

ALTER TABLE PROPERTY 
    ADD CONSTRAINT street_property_fk FOREIGN KEY 
    ( 
     street_id,
     authority_name
    ) 
    REFERENCES STREET 
    ( 
     street_id,
     authority_name
    ) 
;

ALTER TABLE COLLECTION 
    ADD CONSTRAINT truck_collection_fk FOREIGN KEY 
    ( 
     truck_vin
    ) 
    REFERENCES TRUCK 
    ( 
     truck_vin
    ) 
;

ALTER TABLE CONTRACT_WASTE 
    ADD CONSTRAINT wt_ctw_fk FOREIGN KEY 
    ( 
     waste_type_id
    ) 
    REFERENCES WASTE_TYPE 
    ( 
     waste_type_id
    ) 
;

ALTER TABLE BIN_TYPE 
    ADD CONSTRAINT wty_bty_fk FOREIGN KEY 
    ( 
     waste_type_id
    ) 
    REFERENCES WASTE_TYPE 
    ( 
     waste_type_id
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             0
-- ALTER TABLE                             38
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SET ECHO OFF
SPOOL OFF